### ISSUE TITLE
Add F-Droid support

### ISSUE THREAD

**Issue by FabioTacke** [TICESoftware/tice-android#18]
Add build flavor without Google Play Services and Beekeeper

**Comment by paolo-caroni** [comment]
This would be great!

**Comment by FabioTacke** [comment]
We now have an F-droid version ready which waits for approval: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10112

**Comment by ChaosCoder** [comment]
F-droid support is out: https://f-droid.org/en/packages/app.tice.TICE.production/ 🚀
