### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by metezd** [TICESoftware/tice-android#34]
Any plans for multi-language support? I can help translating the app to Turkish

**Comment by ChaosCoder** [comment]
Hey, German and English are already supported, so multi-language support is definitely wanted.

You can either go through our translation website here: https://weblate.tice.software/engage/tice-app/
Or you create a new `app/src/main/res/values-tr/strings.xml` file directly based on the English one `app/src/main/res/values/strings.xml`, start translating and open a Pull Request that we can merge.

**Comment by metezd** [comment]
I couldn't find any info on `README.md`, adding a translation section under **Contribute to TICE** in `README.md` would be useful. I will start translating the app from now on.
